services:
  frontend:
    build: ./card-market-front
    container_name: card-market-front
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
      - NODE_ENV=development
    networks:
      - public-network
  
  node-back:
    build: ./node-back
    container_name: node-back
    ports:
      - "4000:4000"
    networks:
      - public-network
      - back-network

  backend-monolithic:
    build: ./card-market-back/monolithic
    container_name: card-market-back-monolithic
    ports:
      - "8080:8080"
    networks:
      - public-network
      - back-network

  active-mq:
    image: rmohr/activemq
    container_name: card-market-activemq
    ports:
      - "8161:8161"
      - "61613:61613"
      - "61616:61616"
    networks:
      - back-network

  card-generator:
    build: ./card-market-back/card-generator
    container_name: card-market-card-generator
    ports:
      - "8081:8081"
    networks:
      - back-network

  image-generator:
    build: ./card-market-back/image-generator
    container_name: card-market-image-generator
    networks:
      - back-network
    ports:
      - "8082:8082"
    depends_on:
      - image-generator-lib

  description-generator:
    build: ./card-market-back/description-generator
    container_name: card-market-description-generator
    networks:
      - back-network
    ports:
      - "8083:8083"
    depends_on:
      - prompt-generator-lib

  properties-generator:
    build: ./card-market-back/properties-generator
    container_name: card-market-properties-generator
    networks:
      - back-network
    ports:
      - "8084:8084"

  image-generator-lib:
    image: registry.gitlab.com/js-asi2/asi2-resources/img-gene-neural-love-api:v1.1
    container_name: image-generator-lib
    ports:
      - "8090:8080"
    environment:
      - external.iaimgapi.token=${NEURAL_LOVE_API_KEY}
    networks:
      - back-network

  prompt-generator-lib:
    image: ollama/ollama
    container_name: prompt-generator-lib
    ports:
      - "11434:11434"
    volumes:
      - ./card-market-back/ollama:/root/.ollama
    networks:
      - back-network

networks:
  public-network:
    driver: bridge
  back-network:
    driver: bridge