services:
  frontend:
    build: ./card-market-front
    container_name: card-market-front
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
      - NODE_ENV=development
    networks:
      - card-network

  backend:
    build: ./card-market-back
    container_name: card-market-back
    ports:
      - "8080:8080"
    networks:
      - card-network

networks:
  card-network:
    driver: bridge