services:
  frontend:
    build: ./card-market-front
    container_name: card-market-front
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
      - NODE_ENV=development
    networks:
      - card-network

  backend:
    build: ./card-market-back/monolithic
    container_name: card-market-back
    ports:
      - "8080:8080"
    networks:
      - card-network

  active-mq:
    image: rmohr/activemq
    container_name: card-market-activemq
    ports:
      - "8161:8161"
      - "61616:61616"
    networks:
      - card-network

  card-generator:
    build: ./card-market-back/card-generator
    container_name: card-market-card-generator
    networks:
      - card-network

networks:
  card-network:
    driver: bridge