services:
  frontend:
    build: ./card-market-front
    container_name: card-market-front
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
      - NODE_ENV=development