services:

# ActiveMQ
  active-mq:
    image: rmohr/activemq
    container_name: activemq
    ports:
      - "8161:8161"
      - "61613:61613"
      - "61616:61616"
    networks:
      - back-network

# Nginx
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    networks:
      - public-network
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - frontend

# Frontend
  frontend:
    build: ./front
    container_name: front
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
      - NODE_ENV=development
    networks:
      - public-network

# Backends
  backend-monolithic:
    build: ./back/card-market/monolithic
    container_name: card-market-back-monolithic
    ports:
      - "8080:8080"
    networks:
      - public-network
      - back-network

  backend-game:
    build: ./back/game
    container_name: game-back
    ports:
      - "4000:4000"
    networks:
      - public-network
      - back-network

  backend-message:
    build: ./back/message
    container_name: message-back
    ports:
      - "8085:8085"
    networks:
      - public-network
      - back-network

  backend-log:
    build: ./back/log
    container_name: log-back
    ports:
      - "8086:8086"
    volumes:
      - ./back/logs/:/app/log/
    networks:
      - public-network
      - back-network

# Generators
  card-generator:
    build: ./back/card-market/card-generator
    container_name: card-market-card-generator
    ports:
      - "8081:8081"
    networks:
      - public-network
      - back-network

  image-generator:
    build: ./back/card-market/image-generator
    container_name: card-market-image-generator
    networks:
      - back-network
    ports:
      - "8082:8082"
    depends_on:
      - image-generator-lib

  description-generator:
    build: ./back/card-market/description-generator
    container_name: card-market-description-generator
    networks:
      - back-network
    ports:
      - "8083:8083"
    depends_on:
      - prompt-generator-lib

  properties-generator:
    build: ./back/card-market/properties-generator
    container_name: card-market-properties-generator
    networks:
      - back-network
    ports:
      - "8084:8084"

# Generators libs
  image-generator-lib:
    image: registry.gitlab.com/js-asi2/asi2-resources/img-gene-neural-love-api:v1.1
    container_name: image-generator-lib
    ports:
      - "8090:8080"
    environment:
      - external.iaimgapi.token=${NEURAL_LOVE_API_KEY}
    networks:
      - back-network

  prompt-generator-lib:
    image: ollama/ollama
    container_name: prompt-generator-lib
    ports:
      - "11434:11434"
    volumes:
      - ./back/card-market/ollama:/root/.ollama
    networks:
      - back-network

networks:
  public-network:
    driver: bridge
  back-network:
    driver: bridge