# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Back Card Image Generator Maven CI

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn -B package --file ./card-market-back/image-generator/pom.xml

      - name: Run Tests
        run: |
          if [ -d "./card-market-back/image-generator/src/test" ]; then
            echo "Test directory exists, running tests..."
            mvn test --file ./card-market-back/image-generator/pom.xml
          else
            echo "No tests found, skipping test step."
          fi

      - name: Update dependency graph
        run: mvn com.github.ferstl:depgraph-maven-plugin:4.0.1:graph --file ./card-market-back/image-generator/pom.xml