name: Back Card Properties Generator Maven CI

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      # Step to add the local JAR file to the Maven repository
      - name: Install Local Library (colorToproperties-1.1.2.jar)
        run: |
          mvn install:install-file \
            -Dfile=./card-market-back/properties-generator/src/main/resources/colorToproperties-1.1.2.jar \
            -DgroupId=tp.cpe \
            -DartifactId=colorToProperties \
            -Dversion=1.1.2 \
            -Dpackaging=jar

      - name: Build with Maven
        run: mvn -B package --file ./card-market-back/properties-generator/pom.xml

      - name: Run Tests
        run: |
          if [ -d "./card-market-back/properties-generator/src/test" ]; then
            echo "Test directory exists, running tests..."
            mvn test --file ./card-market-back/properties-generator/pom.xml
          else
            echo "No tests found, skipping test step."
          fi

      - name: Update dependency graph
        run: mvn com.github.ferstl:depgraph-maven-plugin:4.0.1:graph --file ./card-market-back/properties-generator/pom.xml
